#SITE YAML
site: TECHTOAM BLOG
  name: The Blog Plus
  url: https://theblogplus.vercel.app/
  description: "A platform for sharing insightful blogs and articles."
  language: en
  author: TECHTOAM,AM industries Official
    name: Ai team & AM team
    email: "techtoambusiness@gmail.com"

settings:
  theme: default
  posts_per_page: 10
  comments_enabled: true
  analytics:
    enabled: true
    provider: GoogleAnalytics
    tracking_id: "G-5L0CS3NR7H
GT-K8GVWNHP"

navigation:
  - label: Home
    link: /
  - label: About
    link: /about
  - label: Blog
    link: /blog
  - label: Contact
    link: /contact

social:
  twitter: "https://twitter.com/TECHTOAM1"
  facebook: "https://facebook.com/techtoam"
  instagram: "https://instagram.com/techtoam"
  for more Social media or Quick Conversation 
  WhatsApp Channel: https://whatsapp.com/channel/0029VaDNi2yLI8YWEqkRbT1d


  -----------------=>

  We are One ♥️
If You Need a help Contact 🙂


𝗔𝗠 𝗶𝗻𝗱𝘂𝘀𝘁𝗿𝘆'𝘀 𝗢𝗳𝗳𝗶𝗰𝗶𝗮𝗹

💻 Website : https://www.techtoam.online

♥️ YouTube :  https://youtube.com/@TECHTOAM

👨‍💻 Github    :  https://github.com/TECHTOAMYT

💬 Telegram : https://t.me/TECHTOAM

💎  Codepen  :  https://codepen.io/techtoamyt

🫂 Join  : https://bit.ly/Join–with_me

🪄 Support Email : Support_noreplay@techtoam.online

♻️ Quick Response G mail : techtoambusiness@gmail.com

YouTube : TECHTOAM

For more Visit Our Website
                                                 Thank You ❤️‍🩹💎🙂
                              𝗔𝗠 𝗶𝗻𝗱𝘂𝘀𝘁𝗿𝘆'𝘀 𝗢𝗳𝗳𝗶𝗰𝗶𝗮𝗹
  
